name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  django-test:
    runs-on: ubuntu-latest
    env:
      MODE: test 
    defaults:
      run:
        working-directory: ./nongjang
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  react-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orange
    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn build --prod

  deploy:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using private key
      run: |
        mkdir -p ~/.ssh/
        echo "$ORANGENONGJANG_KEY" > ~/.ssh/orangenongjang.pem
        sudo chmod 400 ~/.ssh/orangenongjang.pem
        echo "$ORANGENONGJANG_HOST" > ~/.ssh/known_hosts
        ssh $ORANGENONGJANG_USER@ORANGENONGJANG_HOST -i ~/.ssh/orangenongjang.pem "touch hello.txt"
